spring.application.name=expense-tracker-bot


spring.config.import=optional:file:.env

# إعدادات الداتا بيز
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.oianfjiwjoftewafylaj
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# إعدادات Hibernate (تحديد نوع الداتا بيز صراحة)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# إعدادات تليجرام
telegram.bot.username=Mohamed20_Expense_bot
telegram.bot.token=${BOT_TOKEN}

